#!/bin/sh

#SBATCH --job-name=inf_dpa

#SBATCH --output=inf.o

#SBATCH --error=inf.error

#SBATCH --partition=savio

#SBATCH --time=1:00:00

#SBATCH --nodes=4

#SBATCH --ntasks-per-node=20

#SBATCH --cpus-per-task=1

# QoS:

#SBATCH --qos=nuclear_savio_normal

#

# Account:

#SBATCH -A co_nuclear

#SBATCH --mail-user=keckler@berkeley.edu
#SBATCH --mail-type=all

# run command
mpirun -np 4 --map-by ppr:1:node:pe=20 sss2 -omp 20 inf
